### PR TITLE
Replace missing brew with asdf in CI

### PR DESCRIPTION
**Pull request by kachick**
Current CI is failed with brew steps https://github.com/asdf-community/asdf-dprint/actions/runs/4250057277

Looks related to https://github.com/actions/runner-images/issues/6283

### CODE REVIEW

**Comment by kachick** [comment]
Seems there is no activity about half year, so I close this PR.
Thanks for maintaining these plugins.

**Comment by kachick** [comment]
#5 is another solution, it continues to use brew

**Comment by barraponto** [comment]
Yep, but as I was writing it I could not stop wondering whether we should just asdf install it.
I stayed with brew because it would be the least invasive change, though.

**Comment by barraponto** [comment]
Now that I further studied the situation, it seems brew is preferred because it is setup in the [organization-level workflow](https://github.com/asdf-community/.github/blob/master/.github/required-workflows/hygiene.yml) all repos are required to support.

**Pull request closed without merging**
